### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by bhadjajay23** [hyperoslo/CalendarKit#6]
[!] Unable to find a specification for `CalendarKit`
help me for this

**Comment by richardtop** [comment]
Hi, the framework hasn't been finished, so it wasn't published to pods repo.
Still, you can use it if you specify git repository in `podfile`.
`pod 'CalendarKit', :git => 'https://github.com/hyperoslo/CalendarKit.git'`
Time flies, more than a year have passed since I've started this repo, so it may not compile in its current state. You're welcome to submit a pull request, if you're willing to fix those errors.
Also, I can take on it later, when I'll have time for it.
